# Generated by Django 5.2.6 on 2025-09-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coleta',
        ),
        migrations.DeleteModel(
            name='PlanoSaude',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.DeleteModel(
            name='Vantagem',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='servico',
        ),
        migrations.AddField(
            model_name='contato',
            name='botao_texto',
            field=models.CharField(default='ENVIAR SOLICITAÇÃO', max_length=50, verbose_name='Texto do botão'),
        ),
        migrations.AddField(
            model_name='contato',
            name='placeholder_descricao',
            field=models.CharField(default='Descrição (opcional)', max_length=200, verbose_name='Placeholder Descrição'),
        ),
        migrations.AddField(
            model_name='contato',
            name='placeholder_email',
            field=models.CharField(default='Email', max_length=100, verbose_name='Placeholder Email'),
        ),
        migrations.AddField(
            model_name='contato',
            name='placeholder_nome',
            field=models.CharField(default='Seu nome', max_length=100, verbose_name='Placeholder Nome'),
        ),
        migrations.AddField(
            model_name='contato',
            name='titulo',
            field=models.CharField(default='Entre em contato', max_length=200, verbose_name='Título da seção'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.TextField(default='O atendimento mais rápido do mercado', verbose_name='Descrição da seção'),
        ),
    ]
