# Generated by Django 5.2.6 on 2025-09-23 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_coleta_delete_planosaude_delete_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=50)),
                ('vantagens', models.TextField(help_text='Separe cada vantagem por ponto e vírgula (;)')),
                ('classe', models.CharField(choices=[('silver', 'Silver'), ('golden', 'Golden')], default='silver', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='contato',
            name='botao_texto',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='placeholder_descricao',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='placeholder_email',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='placeholder_nome',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='titulo',
        ),
        migrations.AddField(
            model_name='contato',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de envio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='nome',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
