# Generated by Django 5.2.6 on 2025-09-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_planosaude_remove_contato_botao_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vantagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone_svg', models.TextField(verbose_name='Ícone SVG (código <svg>...</svg>)')),
            ],
        ),
    ]
